language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
<<<<<<< HEAD
  app: lab5-addressbook
=======
  app: SYSC_4806_Lab5-addressbook
>>>>>>> 325dcb25888ce9cd57bcb8ba9b2ed2b6795fa473
